---
title: "Call for papers"
---

<h3>Hispanic Linguistics Symposium 2021</h3>

__Conference Dates:__  October 7-9, 2021

__Location:__  Fully virtual conference [Please read the statement from the Organizing Committee on this decision.](virtual.html)

__Abstract Submission Deadline:__  April 30, 2021

__Meeting Description:__ Wake Forest University will host the Hispanic Linguistics Symposium October 7-9, 2021. The Hispanic Linguistics Symposium is an annual conference with a focus on theoretical and applied linguistics in Spanish and Portuguese. Abstracts for paper presentations or posters are invited on any area of Hispanic linguistics, and within any theoretical or quantitative framework.

__Submission Guidelines:__

Format: 

- Papers and posters may be delivered in English, Portuguese, or Spanish.
- Abstracts should be submitted in `.pdf` format and should not exceed one page (1-inch margins, 12-point Times New Roman font), with a second page reserved for examples, tables, and references.
- Abstracts must clearly present a specific thesis statement and include a description of the topic, the approach, and conclusions. To preserve anonymity during the review process, authors should not include their names or otherwise reveal their identity anywhere in the abstract.

Online submission:

- Abstracts must be submitted through [EasyAbs](https://linguistlist.org/confservices/customhome.cfm?Emeetingid=5702JA445876405840A050441) and can be accessed between January 15 - April 30, 2021.
- Please specify the title of the paper, area of research, author names, academic affiliations, and e-mail addresses in the form within the abstract submission system.
- Please also specify whether you wish your submission to be considered for presentation as a paper, a poster, or for both categories.


Workshops: 

The HLS 2021 organizing committee invites proposals for workshops. In the past, HLS has hosted different career workshops, often oriented to junior faculty and graduate students, on a variety of topics (best practices of statistical analysis, getting hired in a teaching-intensive university, *etc*). We would like to continue this tradition in HLS 2021 by inviting proposals for 60 minute workshops. Special consideration will be given to proposals focusing on primary and secondary bilingual education.

Workshop proposals should:

1. Be applied in nature, i.e., offer practical skills to attendees.
2. Be structured as follows: (a) write “WORKSHOP” at the top of the document followed by the suggested title, (b) include a brief overview of the topic or goal of the session (what practical skills will attendees gain?) (c) specify the intended audience (junior faculty, phoneticians, etc), (d) and include a workshop agenda (in the form of a list) structuring the content of the 60 minute session.
3. Be submitted in pdf. format and should not exceed two pages.
4. Not include the name of the organizers, presenters or affiliations.
5. Be submitted through EasyAbs by clicking the option “Poster”.

Notification: 

- Notifications of acceptance / rejection will be sent in June. 

__Contact information:__

Tiffany Judy  
[hlswfu2021@gmail.com](mailto:hlswfu2021@gmail.com)

