---
title: "Coronavirus Policy"
---

In light of the uncertain circumstances created by the COVID-19 pandemic, the HLS organizing committee, with the support of university sponsors, has decided to postpone Wake Forest University’s installment of HLS by one year. We do this with the safety of all conference attendees and the quality of HLS in mind.

We will share more information as it becomes available to us and as we feel certain in sharing it. As much as we were looking forward to welcoming you to Wake Forest University this coming October, we believe this is the best course of action given our current circumstances. More importantly, we look forward to hosting you and HLS in the fall of 2021. Although we will provide more specifics as we are able, we can safely say now that the current set of deadlines for abstract submission, review, notification and registration will be postponed by approximately one year. This is to say that we expect that we will reopen abstract submission sometime January 2021, and close it around the end of April 2021. 

We understand that in one year, the projects associated with abstract submission have changed substantially; thus, those folks who have already submitted abstracts have received separate communications to inform them of options available to them in terms of their abstract. 

Although we were very much looking forward to welcoming the HLS community to Wake Forest University this fall, we think it best to postpone by one year with the hope that 2021 will bring us all more certainty and health. 

The HLS Organizing Committee	