---
title: "Registration"
---

## The Basics:

All attendees must [register via this Google Form](https://forms.gle/vKVcxQgVAkQgP3JV8) by SEPTEMBER 19th, 2021 (11:59PM EST/UTC-4); HLS 2021 is free due to generous WFU funding and virtual modality.

## The Specifics:  

HLS 2021 will be held fully online via Zoom Meetings and Zoom Webinar; all sessions will be synchronous at EST/UTC-4 hours. Neither short presentations nor posters nor workshops will be recorded. It is the responsibility of presenters and attendees to familiarize themselves with Zoom technology prior to HLS 2021. 

As with face-to-face conferences, The Organizing Committee relies on accurate registration information from presenters and attendees to proceed with its planning. Certain components of HLS 2021 may have limited participation capacity; therefore, although HLS 2021 is virtual and free of charge, timely registration is required. 

Presenters (including short presentations, posters and workshops) forfeit their acceptance to present at HLS 2021 if they fail to register via this form by AUGUST 1ST, 2021 (11:59PM EST/UTC-4). In the case of collaborative presentations, all presenters who will be in attendance for the presentation must register. Based on registration, adjustments may be made to the program; therefore, no registration extensions are possible. HLS 2021 attendees (presenters and audience members alike) only gain access to the program, Zoom links, associated information and updates via completion of this registration form. Therefore, if colleagues or students are interested in attending any component of HLS, they too must register via this form. 

The demographic questions below will be used in our funding source reports; 'prefer not to answer' may be written in.

Please direct inquiries to [hlswfu2021@gmail.com](mailto:hlswfu2021@gmail.com)


<!-- 

## Information for presenters and chairs

__Presenters__

- Talk slots will be 30 minutes long (20 minutes of presentation and 10 minutes of Q/A).
- Please, check that the authors’ names and the titles of your talks are accurate [here]().
- There will be a PC in each classroom, so it would be easier if during the break presenters save their presentations on the computers provided.
- If presenters prefer to use your own laptops, there is HDMI connection but note that non-HDMI devices require adapters (please bring your own adapters).
- If there are any technical issues, the tech support can only help with university computers (not personal laptops).
- All classrooms have audio/visual equipment.

__Posters__

- Poster presentations are scheduled on Thursday, so presenters will need to have their posters ready on the first day of the conference.
- Please check the program to make sure that the authors’ names and the titles of your posters are accurate HERE
- Your poster may be 48 X 36 inches or 54 x 36 inches. Posters will be mounted on standing boards that are 70 x 40 inches.

__Chairs__

The chairs for the sessions have been selected from the list of participants. Please, check to see if your name appears as chair of one of the sessions. As much as possible, we tried to match chairs’ specialties with the session they will be chairing.  

Although most of you already have chair experience, we wanted to provide some guidelines to make sure we are all on the same page:

- Chairs should make sure that talks start and finish on time. If one of the presenters of a talk doesn’t show up, please DO NOT MOVE the next talk to fill in the time gap. People will be guiding themselves according to the scheduled program, so if you move a presentation they will miss it.
- Chairs will introduce speakers and their talks. So familiarize yourself with the names, and titles of the presentations in your session.
- Chairs should sit with the speakers in the front row of the audience so they are facing the presentation and can be seen by the speaker while keeping time.
- Number signs will be provided in each room. Please notify speakers when they have 10, 5 and 2 minutes remaining. And, of course, let them know when their time is up.
- If needed, chairs will organize the question section. If there are no volunteers for questions, the chairs will ask the first question.
- If there is no time left for questions, the chairs should recommend that those in attendance save their questions for after the session and/or during the break.


On behalf of the conference organization committee, we thank the participants and chairs for their attendance and support.




-->
