---
title: "Virtual Conference Decision"
---

After continued assessment of the COVID-19 pandemic, hearing from researchers who submitted abstracts to HLS from around the world, and consulting as an organizing committee and with university sponsors, **we have decided to host Wake Forest University’s installment of HLS virtually October 7th-9th, 2021.** While we were looking forward to hosting everyone in person in beautiful Winston Salem (especially during the fall), we have made this difficult decision with the health and safety of our plenaries, panelists and potential attendees, our campus, and our respective communities in mind. With a large number of submissions, distancing protocols may have prevented those who wanted to and were able to attend in person to do so. We also understand the inequities folks face in terms of access to vaccination, research/travel funds, and the ability to safely travel. Thus, we hope that a virtual HLS will be maximally inclusive and allow our individual research agendas and respective fields of inquiry to continue flourishing.

We will share more information as necessary and thank you for your understanding, patience and participation in HLS 2021!

_The Organizing Committee_
